-- Insert fake data for demo
INSERT INTO public.profiles (
  user_id, 
  email, 
  full_name, 
  display_name, 
  bio, 
  tagline,
  user_type,
  location,
  niches,
  content_styles,
  collaboration_types,
  professional_level,
  availability_hours,
  geographic_scope,
  preferred_sectors,
  onboarding_completed
) VALUES 
(
  gen_random_uuid(),
  'emma.creator@demo.com',
  'Emma Johnson',
  'EmmaCreates',
  'Lifestyle and beauty content creator with 200K+ followers. I love sharing daily routines, makeup tutorials, and authentic moments.',
  'Authentic life, beautiful moments ✨',
  'creator',
  '{"country": "United States", "city": "Los Angeles"}',
  '{"lifestyle", "beauty", "fashion"}',
  '{"vlogs", "tutorials", "reviews"}',
  '{"sponsored_posts", "product_placement", "brand_ambassador"}',
  7,
  '15-30',
  'international',
  '{"beauty", "fashion", "health"}',
  true
),
(
  gen_random_uuid(),
  'alex.gamer@demo.com',
  'Alex Chen',
  'AlexGamesMaster',
  'Gaming content creator specializing in FPS and strategy games. Building a community of passionate gamers.',
  'Level up your gaming experience 🎮',
  'creator',
  '{"country": "Canada", "city": "Toronto"}',
  '{"gaming", "tech", "entertainment"}',
  '{"livestreams", "tutorials", "reviews"}',
  '{"sponsored_posts", "long_term_campaigns", "affiliate_marketing"}',
  8,
  '30+',
  'international',
  '{"gaming", "tech", "entertainment"}',
  true
),
(
  gen_random_uuid(),
  'sarah.fitness@demo.com',
  'Sarah Williams',
  'FitWithSarah',
  'Certified personal trainer helping people transform their lives through fitness and nutrition.',
  'Strong is the new beautiful 💪',
  'creator',
  '{"country": "United Kingdom", "city": "London"}',
  '{"fitness", "health", "lifestyle"}',
  '{"educational", "tutorials", "challenges"}',
  '{"sponsored_posts", "brand_ambassador", "event_partnerships"}',
  9,
  '15-30',
  'international',
  '{"health", "sports", "food"}',
  true
) ON CONFLICT (user_id) DO NOTHING;